make -j17 \
ARCH=aarch64 \
CROSS_COMPILE=aarch64-linux-gnu- \
CC=aarch64-linux-gnu-gcc \
PLAT=rcar \
MBEDTLS_COMMON_MK=1 \
LSI=H3 \
LOG_LEVEL=40 \
RCAR_DRAM_SPLIT=1 \
RCAR_GEN3_ULCB=1 \
PMIC_LEVEL_MODE=0 \
RCAR_DRAM_LPDDR4_MEMCONF=1 \
RCAR_LOSSY_ENABLE=1 \
RCAR_BL33_EXECUTION_EL=1  \
RCAR_RPC_HYPERFLASH_LOCKED=0 \
DEBUG=1 \
SPD=opteed \
RCAR_SCMI_PLATFORM=1 \
bl2 bl31 rcar
